name: Build and Test

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout code and initialize submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive  # This will fetch the Unity submodule as well
    
    - name: Install GCC and dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc
    
    - name: Build the project
      run: make  # Run make to compile the project according to the Makefile

    - name: Run tests
      run: |
        # Run the tests assuming an executable named 'test_checkNumber.exe'
        ./tests/test_checkNumber.exe
