name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code and initialize submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: List files in repository
      run: |
        echo "Listing files in the repository"
        ls -alh

    - name: List files in Unity submodule
      run: |
        echo "Listing files in Unity submodule"
        cd Unity
        ls -alh

    - name: Install GCC and dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc

    - name: Build the project
      run: |
        echo "Running make..."
        make  # Run make to compile the project
    
    - name: Compile tests
      run: |
        gcc -o tests/test_checkNumber tests/test_checkNumber.c Unity/src/unity.c src/check_number.c -IUnity/src -I.

    - name: Run tests
      run: |
        echo "Running tests..."
        ./tests/test_checkNumber
