name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in repository
      run: |
        echo "Listing files in the repository"
        ls -alh

    - name: Install GCC and dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc

    - name: Clone Unity (if needed)
      run: |
        if [ ! -d "Unity" ]; then
          git clone https://github.com/ThrowTheSwitch/Unity.git
        fi

    - name: Build the project
      run: |
        echo "Running make..."
        make  # Run make to compile the project
    
    - name: Compile tests
      run: |
        gcc -o tests/test_checkNumber tests/test_checkNumber.c Unity/src/unity.c src/check_number.c -IUnity/src -I.

    - name: Run tests
      run: |
        echo "Running tests..."
        ./tests/test_checkNumber
